# Generated by Django 4.1.3 on 2022-12-13 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeboard', '0004_freeboard_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='freeboard',
            new_name='Post',
        ),
    ]
